name = "decent-bookmarks"
main = "src/worker.js"
compatibility_date = "2024-05-15"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
id = "e827e6c4ed19440389b86616314f4b97"
binding = "FRAMECHAINKV"

[vars]
